### ISSUE TITLE
gtorrent is kill?

### ISSUE THREAD

**Issue by Madotsukii** [gtorrent/gtorrent-core#123]
Can't tell whether we're dead or this is a code freeze, what happened?

**Comment by nyanpasu** [comment]
It's not dead.

Mind you, I've been saying I would try to contribute since the end of November last year, so my word is useless. But I'm working on it, again.

Seeing as how everyone's forgotten about it, I'll start fucking around with it because it seems relatively simple now compared to a while back and because I managed to make more time by stopping IRC and chan lurking.
