### ISSUE TITLE
Central communication

### ISSUE THREAD

**Issue by zovt** [gtorrent/gtorrent-core#128]
Hey guys, great to see the project starting back up. I'm going to start contributing again soon. Is there a place that we can all talk? Is the IRC dead?

**Comment by nyanpasu** [comment]
Hi zovt,

IRC was dead as the project itself for a while. I'll turn on an IRC client one day and start idling there again, but it's probably not happening for the immediate future. I believe @benwaffle and @fuyukaidesu still have a bouncer clocked in.

GitHub has consistently been where we collaborate and where the srs bsns happens, though.

If you want to contribute, you're free to try anything. There is no spec and no direction. Every change is clearly an improvement. Every new bug you introduce would ultimately be a new feature. :)

To make the process simpler though, I suggest creating an issue about your intended changes so that anyone who's on board with your idea can pitch in with suggestions and criticism.

Make a separate branch for your work lah di dah, bam PR. Plans to incorporate tests and so forth.

Little to no conventions here.

Maybe we can have an 8chan board for near-topic discussion and idling? I'd prefer that over IRC.

We could talk here meanwhile, though. I mean #128 is a pretty neat number.

I merged in the wip/rss branch before it was completed because I didn't like how gtorrent-gtk's master branch relied on a wip branch from core. Thus, getting RSS from a wip state to a usable state is a priority.

There was a list of planned features tucked inside another issue over [here](https://github.com/gtorrent/gtorrent-gtk/issues/87)

**Comment by zovt** [comment]
OK cool. I'll start up once I have time.

**Comment by nyanpasu** [comment]
Thanks.

By the way, you should have posted another one more time, instead of editting your original post. People won't get notifications for edits.

If I wasn't clearing through my backlock I might've missed it.

**Comment by zovt** [comment]
Yep, my bad.
